"""
Data visualisation module - creates charts and graphs using Matplotlib.
   
All visual outputs (pie charts, bar charts, etc.) are generated by functions
in this module. No user input or data processing should occur here.
"""
  
import matplotlib.pyplot as plt
import numpy as np

# Try to use a font that handles special characters better
plt.rcParams['font.sans-serif'] = ['Arial Unicode MS', 'DejaVu Sans']

def create_pie_chart(park_counts):
    """
    Creates a pie chart showing the distribution of reviews across parks.
    
    Args:
        park_counts (dict): Park names as keys, review counts as values
    """
    parks = list(park_counts.keys())
    counts = list(park_counts.values())
    
    # Clean up park names for display
    clean_names = [name.replace('_', ' ').replace('Disneyland', 'DL ') for name in parks]
    
    fig, ax = plt.subplots(figsize=(10, 8))
    
    wedges, texts, autotexts = ax.pie(counts, 
                                       labels=clean_names, 
                                       autopct='%1.1f%%',
                                       startangle=90,
                                       textprops={'fontsize': 11})
    
    # Style the percentage text
    for autotext in autotexts:
        autotext.set_color('white')
        autotext.set_fontweight('bold')
    
    ax.set_title('Distribution of Reviews Across Disneyland Parks', 
                 fontsize=14, 
                 fontweight='bold',
                 pad=20)
    
    plt.tight_layout()
    plt.show()

def create_top_locations_bar_chart(location_averages, park_name):
    """
    Creates a horizontal bar chart showing top 10 locations by average rating.
    
    Args:
        location_averages (dict): Location as keys, average rating as values
        park_name (str): Name of the park being analysed
    """
    # Sort by rating descending and take top 10
    sorted_locations = sorted(location_averages.items(), key=lambda x: x[1], reverse=True)[:10]
    
    if not sorted_locations:
        print(f"No data available for {park_name}")
        return
    
    locations = [item[0] for item in sorted_locations]
    ratings = [item[1] for item in sorted_locations]
    
    fig, ax = plt.subplots(figsize=(12, 6))
    
    # Create horizontal bars
    bars = ax.barh(locations, ratings, color='steelblue', edgecolor='navy', alpha=0.8)
    
    # Add value labels at the end of each bar
    for i, (bar, rating) in enumerate(zip(bars, ratings)):
        ax.text(bar.get_width() + 0.05, bar.get_y() + bar.get_height()/2, 
                f'{rating}', va='center', fontsize=10, fontweight='bold')
    
    ax.set_xlabel('Average Rating (out of 5)', fontsize=12, fontweight='bold')
    ax.set_title(f'Top 10 Locations by Average Rating - {park_name.replace("_", " ")}', 
                 fontsize=14, fontweight='bold')
    ax.set_xlim(0, 5.5)
    ax.grid(axis='x', linestyle='--', alpha=0.3)
    
    plt.tight_layout()
    plt.show()

def create_monthly_ratings_chart(monthly_averages, park_name):
    """
    Creates a bar chart showing average rating per month for a specific park.
    
    Args:
        monthly_averages (dict): Month names as keys, average ratings as values
        park_name (str): Name of the park being analysed
    """
    # Preserve month order
    months = ['January', 'February', 'March', 'April', 'May', 'June',
              'July', 'August', 'September', 'October', 'November', 'December']
    
    ratings = [monthly_averages.get(month, 0) for month in months]
    
    fig, ax = plt.subplots(figsize=(14, 6))
    
    # Create bars with gradient-like colours
    colors = plt.cm.viridis(np.linspace(0.3, 0.9, 12))
    bars = ax.bar(months, ratings, color=colors, edgecolor='darkgreen', alpha=0.8)
    
    # Add value labels on top of bars
    for bar, rating in zip(bars, ratings):
        if rating > 0:
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.05,
                    f'{rating}', ha='center', va='bottom', fontsize=9, fontweight='bold')
    
    ax.set_ylabel('Average Rating (out of 5)', fontsize=12, fontweight='bold')
    ax.set_xlabel('Month', fontsize=12, fontweight='bold')
    ax.set_title(f'Monthly Average Ratings - {park_name.replace("_", " ")}', 
                 fontsize=14, fontweight='bold')
    ax.set_ylim(0, 5.5)
    ax.grid(axis='y', linestyle='--', alpha=0.3)
    
    # Rotate x-axis labels for better readability
    plt.xticks(rotation=45, ha='right')
    
    plt.tight_layout()
    plt.show()
